# Azure Pipelines -- JMHARDISON org.
trigger:
- master

resources:
  - repo: self
    fetchDepth: 1

#jobs to do dev or prod builds
jobs:
  - job: BuildStage
    pool:
      name: 'OnPremises'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.Repository.LocalPath)' 
        includeRootFolder: true
        archiveType: 'zip' # Options: zip, 7z, tar, wim
        #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
        archiveFile: '$(Build.ArtifactStagingDirectory)/zips/$(Build.BuildId).zip' 
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'zipfile'
        targetPath: '$(Build.ArtifactStagingDirectory)/zips'
  - job: ReleaseStage
    pool:
      name: 'OnPremises'
    dependsOn: BuildStage
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) #master
    steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/zips
    - task: LambdaDeployFunction@1
      displayName: 'Deploy Lambda Function: isGameOnline'
      inputs:
        awsCredentials: 'AWS-JMH'
        regionName: 'us-east-1'
        functionName: isGameOnline
        localZipFile: '$(Build.ArtifactStagingDirectory)/zips/$(Build.BuildId).zip'

